In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
#  sentences:
sent=[
    'the glass  of milk',
    'the glass of juice',
    'im a good boy',
    'im a good developer',
    'undertanding the meaning of the word',
]

In [3]:
sent

['the glass is full of milk',
 'the glass of juice',
 'im a good boy',
 'im a good developer',
 'undertanding the meaning of the word']

In [11]:
# define vclubalry size
voc_size=10000
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4998, 3650, 6753, 1736],
 [4998, 3650, 6753, 2945],
 [8595, 2548, 3866, 9408],
 [8595, 2548, 3866, 8524],
 [869, 4998, 3367, 6753, 4998, 4824]]

In [7]:
#  word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential


In [ ]:
import numpy as np

In [12]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4998 3650 6753 1736]
 [   0    0    0    0 4998 3650 6753 2945]
 [   0    0    0    0 8595 2548 3866 9408]
 [   0    0    0    0 8595 2548 3866 8524]
 [   0    0  869 4998 3367 6753 4998 4824]]


In [13]:
# feature represention
dim=10

In [14]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

s:\anaconda\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [16]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [17]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 252ms/step


array([[[-3.50927934e-02, -3.08794733e-02,  1.77264847e-02,
         -3.97752635e-02, -1.27968788e-02, -5.89523464e-03,
         -1.63780339e-02, -3.84343974e-02, -2.03263760e-03,
          4.55095060e-02],
        [-3.50927934e-02, -3.08794733e-02,  1.77264847e-02,
         -3.97752635e-02, -1.27968788e-02, -5.89523464e-03,
         -1.63780339e-02, -3.84343974e-02, -2.03263760e-03,
          4.55095060e-02],
        [-3.50927934e-02, -3.08794733e-02,  1.77264847e-02,
         -3.97752635e-02, -1.27968788e-02, -5.89523464e-03,
         -1.63780339e-02, -3.84343974e-02, -2.03263760e-03,
          4.55095060e-02],
        [-3.50927934e-02, -3.08794733e-02,  1.77264847e-02,
         -3.97752635e-02, -1.27968788e-02, -5.89523464e-03,
         -1.63780339e-02, -3.84343974e-02, -2.03263760e-03,
          4.55095060e-02],
        [-1.74662694e-02,  4.47855033e-02, -2.05439460e-02,
         -3.98018472e-02, -1.65982135e-02,  6.99720532e-03,
          2.65910886e-02, -9.00347158e-03, -3.569300

In [19]:
embedded_docs[0]

array([   0,    0,    0,    0, 4998, 3650, 6753, 1736])